rss_dict = {
    "csvn": "https://dangcongsan.vn/so-do-website",
    "rfa": "https://www.rfa.org/vietnamese/rss",
    "lifefinance": "https://www.litefinance.com/vi/rss/",
    "afamily": "https://afamily.vn/rss.chn",
    "bongda": "https://www.bongda.com.vn/main-rss.html",
    "vnexpress": "https://vnexpress.net/rss",
    "thanh_nien": "https://thanhnien.vn/rss/",
    "nguoi_lao_dong": "https://nld.com.vn/rss/",
    "lao_dong": "https://laodong.vn/rss",
    "cafebiz": "https://cafebiz.vn/rss.chn",
    "24h": "https://www.24h.com.vn/guest/RSS/",
    "gamek": "https://gamek.vn/rss.chn",
    "vietnamnet": "http://vietnamnet.vn/vn/rss/",
    "tuoi_tre": "https://tuoitre.vn/rss.htm",
    "dan_tri": "http://dantri.com.vn/rss.htm",
    "soha": "http://soha.vn/rss.htm",
    "game4v": "http://game4v.com/feed",
    "vtv": "https://vtv.vn/rss.htm",
    "the_thao_van_hoa": "https://thethaovanhoa.vn/rss.rss",
    "bao_tin_tuc": "https://baotintuc.vn/rss.rss",
    "ttxvn": "https://vnanet.vn/vi/rss/",
    "tai_chinh_viet_nam": "https://vietnamfinance.vn/rss.htm",
    "bao_chinh_phu": "https://baochinhphu.vn/Rss/",
    "tien_phong": "https://www.tienphong.vn/rss.tpo",
    "bao_phap_luat": "https://baophapluat.vn/rss.html",
    "dan_viet": "https://danviet.vn/danh-muc.rss",
    "tri_thuc": "https://trithucvn.org/rssfeed",
    "vtc_news": "https://vtc.vn/main-rss.html",
    "bao_dan_toc": "https://baodantoc.vn/rss.htm",
    "stockbiz": "https://www.stockbiz.vn/RSS.aspx",
    "vepf": "https://vepf.vn/vi/rss.html",
    "bao_hiem_xa_hoi": "https://baohiemxahoi.gov.vn/pages/rss.aspx",
    "vass": "https://vass.gov.vn/pages/rss.aspx",
    "voa": "https://www.voatiengviet.com/rssfeeds",
    "tieu_dung_viet_nam": "https://tieudungvietnam.vn/rss.html",
    "antv": "https://www.antv.gov.vn/rss.html"
}

single_feeds = {
    "trainghiemso": ["https://trainghiemso.vn/feed/"],
    "vov1": [
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=2",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=3",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=4",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=190",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=73",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=100",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=184",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=178",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=185",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=11",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=12",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=14",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=29",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=84",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=127",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=128",
        'http://vov1.vov.gov.vn/Feed.aspx?CatId=133',
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=5",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=199",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=15",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=16",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=17",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=18",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=48",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=6",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=88",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=19",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=31",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=135",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=136",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=7",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=33",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=34",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=35",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=55",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=9",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=36",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=174",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=21",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=22",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=137",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=71",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=152",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=25",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=140",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=50",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=103",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=58",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=59",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=64",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=65",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=67",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=68",
        "http://vov1.vov.gov.vn/Feed.aspx?CatId=129"
    ],
    # "vov3": [
    #     "https://vov3.vov.gov.vn/Feed.aspx?CatId=1",
    #     "https://vov3.vov.gov.vn/Feed.aspx?CatId=2",
    #     "https://vov3.vov.gov.vn/Feed.aspx?CatId=7",
    #     "https://vov3.vov.gov.vn/Feed.aspx?CatId=8",
    #     "https://vov3.vov.gov.vn/Feed.aspx?CatId=9",
    #     "https://vov3.vov.gov.vn/Feed.aspx?CatId=10",
    #     "https://vov3.vov.gov.vn/Feed.aspx?CatId=11",
    #     "https://vov3.vov.gov.vn/Feed.aspx?CatId=12",
    #     "https://vov3.vov.gov.vn/Feed.aspx?CatId=3",
    #     "https://vov3.vov.gov.vn/Feed.aspx?CatId=4",
    #     "https://vov3.vov.gov.vn/Feed.aspx?CatId=5",
    #     "https://vov3.vov.gov.vn/Feed.aspx?CatId=6"
    # ]   
}